### ISSUE TITLE
Hoher Energieverbrauch

### ISSUE THREAD

**Issue by amuessig** [obama/adventskalender-dashboard#23]
Ich habe festgestellt, dass der Energieverbrauch (und CPU Load) stark ansteigt wenn ich das Dashboard anzeige oder auch mit dem Dashboard durch die Seiten rotiere.

Kann man hier ggf. noch ein wenig optimieren?

Firefox `v 63.3.0`

**Comment by obama** [comment]
also das dashboard selber dürfte keine energie verbrauchen, lediglich der pulsierende button sorgt für ständige aktivität, aber bei mir hält sich das bei 2% circa.

wenn man durch du seiten rotiert, dann erzeugen die seiten die CPU last. wenn dort schnee effekte sind dann kann das recht viel last erzeugen.

**Comment by amuessig** [comment]
Bei mir verbraucht das Dashboard im Firefox 50% mehr CPU Load als wenn ich den Firefox normal verwende.. Ich habe dabei keine Seiten geladen. Daher wäre eine Einstellung, das pulsieren abstellen zu können, gerne gesehen :)
