### ISSUE TITLE
Statusleiste zeigt Anzahl aller Seiten

### ISSUE THREAD

**Issue by amuessig** [obama/adventskalender-dashboard#24]
Die Statusleiste beim Ausfüllen der Gewinnspiele zeigt die Anzahl aller Gewinnspiele an, zum Beispiel: 43/252. Hier sind die deaktivierten ebenfalls hinein gezählt.

Kann man hier bitte lediglich die nicht deaktivierte Anzahl an Gewinnspielen anzeigen?

**Comment by obama** [comment]
8a9fd90 behebt dieses problem
